### ISSUE TITLE
Markdown Component

### ISSUE THREAD

**Issue by sapegin** [sapegin/react-components#1]
_Only components that render Markdown as React components, not as HTML string inside `dangerouslySetInnerHTML`._

## ~~[markdown-to-react-components](https://github.com/christianalfoni/markdown-to-react-components)~~

**Deprecated**

Based on Marked.

Pros:
- Requires no Webpack hacks.

Cons:
- Based on Marked.
- Tries to highlight code with Prism by default, which is not “included”.

## [markdown-react-js](https://github.com/alexkuz/markdown-react-js)

Based on Markdown It.

Cons:
- No HTML support.
- Requires Webpack hacks.
- No updates since November 2015.

## [remark-react](https://github.com/mapbox/remark-react)

Based on Remark.

Cons:
- Requires too much Webpack hacks.

## [markdown-to-jsx](https://github.com/yaycmyk/markdown-to-jsx)

Based on Remark.

Pros:
- HTML and tables support.

## [react-markdown](https://github.com/rexxars/react-markdown)

Based on CommonMark.

Cons:
- No tables support.
- Requires Webpack hacks.

## [simple-markdown](https://github.com/Khan/simple-markdown)

Pros:
- No dependencies.
- Very small (less than 4 KB which is ~10 times smaller than other libraries)

Cons:
- No HTML support.

## [remarkable-react](https://github.com/HHogg/remarkable-react)

Based on Remarkable.

Cons:
- No HTML support.

## [Marksy](https://github.com/cerebral/marksy)

Based on Marked.

Pros:
- Based on Marked (smaller then other libraries).
- Requires no webpack hacks.

Cons:
- Based on Marked.

**Comment by bebraw** [comment]
For what it's worth, I wrote [html-webpack-remark-plugin](https://www.npmjs.com/package/html-webpack-remark-plugin) to make it a little easier. That could be one direction.

**Comment by quantizor** [comment]
@sapegin what hack does md2jsx need? Happy to try and help alleviate any pain there.

**Comment by sapegin** [comment]
@probablyup I think it was about json-loader but since webpack 2 it doesn’t matter so I could remove that ;-)

**Comment by quantizor** [comment]
Ahh, might be something deep in remark. Good to know.

**Comment by sapegin** [comment]
@probablyup I remember that one of the component required a `.json` extension in webpack config but don’t remember which one.
